sudo: required
language: python
python:
    - 2.7
    - 3.4
    - 3.5
    - 3.6
env:
    - TRAVIS_NODE_VERSION="4"
    - TRAVIS_NODE_VERSION="6"
# install dependencies
install: 
    - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
    - sudo npm install -g yarn
    - yarn
    - pip install -r requirements/development.txt
# style guide test, temp ignore of some django generated code
before_script:
    - flake8 --exclude=migrations,settings,manage.py,.venv,docs,invoicing .
# run main tests
script:
    - coverage run --source=core,api manage.py test
# report code coverage to coveralls
after_success:
    - coveralls
