language: python
python:
    - 2.7
    - 3.4
    - 3.5
    - 3.6
install: 
    - pip install -r requirements/development.txt
# many excludes here are currently temporary
before_script:
    - flake8 --exclude=.venv,migrations .
script:
    - coverage run --source=core,api manage.py test
after_success:
    - coveralls
