sudo: false
dist: trusty
language: python
cache:
    pip: true
    directories:
        - node_modules
python:
    - 2.7
    - 3.4
    - 3.5
    - 3.6
env:
    - TRAVIS_NODE_VERSION="4" 
    - TRAVIS_NODE_VERSION="6"
addons:
    sauce_connect: true
install: 
    - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
    - npm install -g gulp-cli && npm install
    - pip install -r requirements/development.txt
before_script:
    - gulp lint
script:
    - coverage run --source=core,api manage.py test
after_success:
    - coveralls
